#!/bin/bash
#SBATCH --job-name="nbody_mpi_test"
#SBATCH --output="nbody_mpi_test.%j.%N.out"
#SBATCH --partition=shared
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=5
#SBATCH --mem=8G
#SBATCH --account="slo106"
#SBATCH --time=00:10:00

set -euo pipefail

BODIES=10
STEPS=2

srun -n 1 ./nbody_octree_mpi "$BODIES" "$STEPS"
srun -n 3 ./nbody_octree_mpi "$BODIES" "$STEPS"
srun -n 5 ./nbody_octree_mpi "$BODIES" "$STEPS"
